# Generated by Django 3.2.5 on 2021-08-14 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_alter_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='password1',
        ),
    ]
