# Generated by Django 3.2.5 on 2021-08-26 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_auto_20210817_1650'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
