# Generated by Django 3.2.5 on 2021-08-27 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_delete_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AddField(
            model_name='user',
            name='adress',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
