# Generated by Django 3.2.5 on 2021-08-27 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_auto_20210827_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='adress',
        ),
    ]
